//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tieuluan_ban_giay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danh_Gia
    {
        public int ID { get; set; }
        public string Noi_Dung { get; set; }
        public System.DateTime Ngay_Danh_Gia { get; set; }
        public int So_Sao { get; set; }
        public int ID_Khach_Hang { get; set; }
        public int ID_San_Pham { get; set; }
    
        public virtual Giay Giay { get; set; }
        public virtual Khach_Hang Khach_Hang { get; set; }
    }
}
