//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tieuluan_ban_giay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don_Dat_Hang
    {
        public int So_Don_Hang { get; set; }
        public Nullable<int> Ma_Khach_Hang { get; set; }
        public string Ngay_Dat_Hang { get; set; }
        public Nullable<decimal> TriGia { get; set; }
        public string DaGiao { get; set; }
        public string NgayGiaoHang { get; set; }
        public string Ten_Khach_Hang { get; set; }
        public string DiaChi_Khach_Hang { get; set; }
        public string DienThoai_khach_Hang { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string HinhThucGiaoHang { get; set; }
    
        public virtual Khach_Hang Khach_Hang { get; set; }
    }
}
